### ISSUE TITLE
Can't find file '/rr/base/explainable_qa/baselines/ib_train_sentence.py'

### ISSUE THREAD

**Issue by homoscribens** [princeton-nlp/rationale-robustness#1]
I tried to run `./scripts/run_multirc.sh vib`, but the file 'ib_train_sentence.py' in 'rr/base/explainable_qa/baselines' is missing.
Though I found the file in 'in 'rr/base/explainable_qa/information_bottleneck', it seems not working with environment in the requirments.

The whole error massasge is following

> /PATH/bin/python: can't open file '/PATH/rationale-robustness/rr/base/explainable_qa/baselines/ib_train_sentence.py': [Errno 2] No such file or directory
Killing subprocess 1734334
Traceback (most recent call last):
  File "/PATH/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/PATH/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/PATH/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/PATH/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/PATH/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/PATH/bin/python', '-u', 'ib_train_sentence.py', '--local_rank=0', '--data_dir', '/PATH/rationale-robustness/rr/base/explainable_qa/data/multirc', '--output_dir', '/PATH/rationale-robustness/rr/base/explainable_qa/out/multirc_vib', '--model_type', 'distilbert_hard_gated_sent', '--overwrite_output_dir', '--do_train', '--do_eval', '--eval_split', 'val', '--max_seq_length', '512', '--max_query_length', '32', '--num_train_epochs', '10', '--max_num_sentences', '15', '--wait_step', '10', '--evaluate_during_training', '--logging_steps', '500', '--save_steps', '5000', '--local_rank', '-1', '--classes', 'True', 'False', '--chunk_size', '10', '--beta', '0.1', '--threshold', '0.25', '--dataset-name', 'multirc', '--bottleneck-type', 'vib', '--model-name', 'multirc_vib', '--pred-dir', 'multirc']' returned non-zero exit status 2.

**Comment by howard50b** [comment]
Hi @Dash400air, 

Thanks for reaching out. Just a quick check, have you set the path in the run script [here](https://github.com/princeton-nlp/rationale-robustness/blob/main/scripts/run_multirc.sh#L3)?

**Comment by homoscribens** [comment]
Hello @howard50b ,
Thanks for the quick reply!

Yes, I set the absolute path in there.

**Comment by howard50b** [comment]
I think I mistakenly specified an incorrect path in the run script. Just corrected it. Can you pull and try again?

**Comment by homoscribens** [comment]
The error was succesfully solved, but I got another error. It seems 'ib_train_sentence.py' trying to import some functions from python files in the directory 'eraser', and I cannot find the file in the repository.

> Traceback (most recent call last):
  File "/PATH/rationale-robustness/rr/base/explainable_qa/information_bottleneck/ib_train_sentence.py", line 31, in <module>
    from eraser.rationale_benchmark.utils import (
ModuleNotFoundError: No module named 'eraser'

I found 'eraser' directory in original repo of VIB. I copied it to this repo and executed the run file again, but it failed because of the absence of multirc dataset.

> FileNotFoundError: [Errno 2] No such file or directory: '/PATH/rationale-robustness/rr/base/explainable_qa/data/multirc/train.jsonl'

**Comment by howard50b** [comment]
I see. Let me test the whole training script again a bit more thoroughly and get back to you. Sorry for the trouble.

**Comment by homoscribens** [comment]
No problem! Thanks for your help.

**Comment by howard50b** [comment]
I made the data more readily available and pushed the missing files. Can you try again?

**Comment by homoscribens** [comment]
Successfully, training has been runned! Thanks for the work.
But unfortunately I got another error again. It seems system tried to save file and then raised error, which states some files are missing.
Also, it failed to make directory for the checkpoint file.
I reckon this procedure attempts to save weights and resulted in failure.

Around the line 319 in 'ib_train_sentence.py' might be the point, I think.

> 3869897 MainThread loading weights file /home/s2110137/projects/robust_xnlp/baselines/rationale-robustness/rr/base/explainable_qa/out/multirc_vib/best_model/pytorch_model.bin

> Traceback (most recent call last):
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/n/fs/nlp-hc22/rationale-robustness/predictions/multirc/vib/multirc_vib/original'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/n/fs/nlp-hc22/rationale-robustness/predictions/multirc/vib/multirc_vib'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/n/fs/nlp-hc22/rationale-robustness/predictions/multirc/vib'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/n/fs/nlp-hc22/rationale-robustness/predictions/multirc'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/n/fs/nlp-hc22/rationale-robustness/predictions'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/n/fs/nlp-hc22/rationale-robustness'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/n/fs/nlp-hc22'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/n/fs'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/s2110137/projects/robust_xnlp/baselines/rationale-robustness/rr/base/explainable_qa/information_bottleneck/ib_train_sentence.py", line 973, in <module>
    main()
  File "/home/s2110137/projects/robust_xnlp/baselines/rationale-robustness/rr/base/explainable_qa/information_bottleneck/ib_train_sentence.py", line 956, in main
    result = evaluate(args, model_params, model, tokenizer, prefix='', output_examples=True, split=args.eval_split)
  File "/home/s2110137/projects/robust_xnlp/baselines/rationale-robustness/rr/base/explainable_qa/information_bottleneck/ib_train_sentence.py", line 480, in evaluate
    Path(full_pred_dir).mkdir(parents=True, exist_ok=True)
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  [Previous line repeated 5 more times]
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/n'
Killing subprocess 1007342
Traceback (most recent call last):
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/s2110137/conda/envs/Chen/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/s2110137/conda/envs/Chen/bin/python', '-u', 'ib_train_sentence.py', '--local_rank=0', '--data_dir', '/home/s2110137/projects/robust_xnlp/baselines/rationale-robustness/rr/base/explainable_qa/data/multirc', '--output_dir', '/home/s2110137/projects/robust_xnlp/baselines/rationale-robustness/rr/base/explainable_qa/out/multirc_vib', '--model_type', 'distilbert_hard_gated_sent', '--overwrite_output_dir', '--do_train', '--do_eval', '--eval_split', 'val', '--max_seq_length', '512', '--max_query_length', '32', '--num_train_epochs', '10', '--max_num_sentences', '15', '--wait_step', '10', '--evaluate_during_training', '--logging_steps', '500', '--save_steps', '5000', '--local_rank', '-1', '--classes', 'True', 'False', '--chunk_size', '10', '--beta', '0.1', '--threshold', '0.25', '--dataset-name', 'multirc', '--bottleneck-type', 'vib', '--model-name', 'multirc_vib', '--pred-dir', 'multirc']' returned non-zero exit status 1.

**Comment by howard50b** [comment]
Ah so this must be an issue in this [line](https://github.com/princeton-nlp/rationale-robustness/blob/main/rr/base/explainable_qa/information_bottleneck/ib_train_sentence.py#L846). Make a folder called `predictions` in your repo folder and set the `--base-pred-dir` to your path. It's meant to save your model's checkpoints and predictions in this dir.

**Comment by homoscribens** [comment]
Finally everything worked! Thank you very much for your support. It hepls me a lot.

I have one last question
I wonder if rationale supervision is functioning. I runned VIB with '--use-gold-rationale' as to README, but I did not find the loss of it and any implimentation, which supervises rationale except this [code](https://github.com/princeton-nlp/rationale-robustness/blob/362c5737773fc59a968e0ef8be1e57ac9f5f6854/rr/base/explainable_qa/information_bottleneck/ib_train_sentence.py#L834), not used in the file. (I'm sorry if I missed the codes)

Btw, I found the best model file 'pytorch_model.bin' in 'rr/base/explainable_qa/information_bottleneck/out/best_model', not in 'predictions'. I estimate i have to chane the path of '--output_dir' in run_multirc.sh

**Comment by homoscribens** [comment]
@howard50b 
How are you doing? It's really helps me if you answer this last question.

**Comment by howard50b** [comment]
Hi @Dash400air, my apologies for missing the notification. For using the `*-sup` models, you need to set the `bottleneck_type` to `vib_semi` ([here](https://github.com/princeton-nlp/rationale-robustness/blob/362c5737773fc59a968e0ef8be1e57ac9f5f6854/scripts/run_multirc.sh#L43)) as it is used to set [the bottleneck-type flag](https://github.com/princeton-nlp/rationale-robustness/blob/362c5737773fc59a968e0ef8be1e57ac9f5f6854/rr/base/explainable_qa/information_bottleneck/ib_train_sentence.py#L843), which consequently set [the semi_supervised flag](https://github.com/princeton-nlp/rationale-robustness/blob/362c5737773fc59a968e0ef8be1e57ac9f5f6854/rr/base/explainable_qa/information_bottleneck/ib_train_sentence.py#L897), and finally used [here with the gamma variable](https://github.com/princeton-nlp/rationale-robustness/blob/362c5737773fc59a968e0ef8be1e57ac9f5f6854/rr/base/explainable_qa/information_bottleneck/gated_explainer.py#L540).

Sorry for the convoluted logic. This is built on top of another repo so there's quite a bit of patch work. But thanks for raising this! I'll add to the readme to clarify this.

**Comment by homoscribens** [comment]
The codes ran properly and supervision for vib seems working.
Then I close this issue hereby.
Thanks for your support again, @howard50b !
