### ISSUE TITLE
file 'rr.attacks.convert_queries' is missing.

### ISSUE THREAD

**Issue by homoscribens** [princeton-nlp/rationale-robustness#2]
Hi, Sorry for asking again and again, but I have an issue about creating attacked dataset.

I'm trying to create attacked multirc as to the README.
I ran `python -m rr.attacks.aug_and_cache_data --dataset-name fever --aug-method addsent --attack-dir addsent --insert_pos 0`, but got import error which stated `rr.attacks.convert_queries` is missing.

Could you check this out? It would be appreciated, if you help me.

**Comment by howard50b** [comment]
Hi, apologies again for the trouble. The missing files are added now!

**Comment by homoscribens** [comment]
Thanks for the update!
It seems that the script uses glove vector. I would like to ask you which one you used for the research.
And I want to confirm it is correct that the code opens glove vector file, which is txt, with json file [here](https://github.com/princeton-nlp/rationale-robustness/blob/e41c44effaaf9d083954d2ff32ea839686529c92/rr/attacks/aug_and_cache_data.py#L379).

**Comment by howard50b** [comment]
Hi, that would be the file you save from [here](https://github.com/princeton-nlp/rationale-robustness/blob/main/rr/attacks/find_nearby_words.py#L69) and the GloVe used was `glove.6B.100d.txt`.

**Comment by howard50b** [comment]
I'll close this issue for now. Feel free to reopen if there's more question!
