### ISSUE TITLE
Beer and Hotel Datasets

### ISSUE THREAD

**Issue by meng-wenlong** [princeton-nlp/rationale-robustness#3]
Hi! It is a wonderful work! Could you please open-source Beer and Hotel datasets or just tell me where to find these datasets. I'm learning NLP rationalization. Please!

**Comment by howard50b** [comment]
Hi @meng-wenlong, 
Unfortunately the [official data source](https://snap.stanford.edu/data/web-BeerAdvocate.html) has removed public access to the dataset. You can find the alternative here: https://github.com/YujiaBao/R2A

**Comment by meng-wenlong** [comment]
The alternative works! Thanks for your reply! But, I find it strange that `hotel_vib`'s dev acc would get smaller with training. I can only get a 0.92 dev acc rather than 0.94 in the paper. I guess there might be something wrong in `run_hotel.sh`, as it's vib parameters are the same as `run_beer.sh`.

**Comment by howard50b** [comment]
Thanks for spotting that! I've updated the script to replace `beer` to `hotel` in the script. That said, the parameters used for hotel and beer are pretty much the same. Maybe you can try using different seeds? I remember there's a little variance for these sentiment datasets.

**Comment by howard50b** [comment]
I'll close it for now. Feel free to reopen if there's further question!
