### ISSUE TITLE
Issue of lp_sparsemap

### ISSUE THREAD

**Issue by yangshuodelove** [princeton-nlp/rationale-robustness#4]
Hi, when I pip install lp_sparsemap, I found the issue below. Could you help me to solve it? Thanks in advance. 
![image](https://user-images.githubusercontent.com/24713662/212570663-87e55e74-cbeb-4dcf-8756-46f511759d82.png)

**Comment by howard50b** [comment]
Hi @yangshuodelove thanks for reaching out! Can you try running `pip install -e .` from  this repo: https://github.com/nunonmg/lp-sparsemap ?

**Comment by yangshuodelove** [comment]
Thanks @howard50b It works.
